---
 - name: Playbook with tags
   hosts: planetexpress
   connection: ansible.builtin.ssh

   tasks:
     - name: Tag
       debug:
         msg: "tag1"
       tags:
       - tag1

     - name: Tag
       debug:
         msg: "tag2"
       tags:
       - tag2

     - name: Tag
       debug:
         msg: "tag1M"
       tags:
       - tag1
       - tagM  

     - name: Tag
       debug:
         msg: "no tag"
