---
- name: A Play to play with Python
  hosts: localhost

  vars:
    test_list:
      - '192.168.2.1'
      - '10.10.0.2'
      - 'host.example.org'
      - '192.168.70.0/24'
      - 'fe80::100/10'
      - 'True'
      - 'Witcher 3: The Wild Hunt'
      - 'Earl Grey Tea, hot'
    mytest_string: "NCC1701 USS Enterprise"
    myaddresses: ['192.168.2.101', '10.0.3.50', '171.172.32.1']

  tasks:

  - name: Pop the number 50 on the screen
    debug:
      msg: "{{ (myaddresses|ansible.utils.ipaddr('10.0.0.0/8')).split('.')[0] }}"

  - name: Pop the number 50 on the screen
    debug:
      msg: "{{ (myaddresses|ansible.utils.ipaddr('10.0.0.0/8'))[0].split('.')[1] }}"

  - name: Pop the number 50 on the screen
    debug:
      msg: "{{ (myaddresses|ansible.utils.ipaddr('10.0.0.0/8'))[0].split('.')[2] }}"
        
  - name: Pop the number 50 on the screen
    debug:
      msg: "{{ (myaddresses|ansible.utils.ipaddr('10.0.0.0/8'))[0].split('.')[3] }}"

