---
- name: Query an Open API
  hosts: localhost
  connection: local

  vars:
      pika: 'https://pokeapi.co/api/v2/pokemon?offset=0&limit=2000'

  tasks:
  - name: Send an HTTP GET to API
    ansible.builtin.uri:
      method: GET
      url: "{{ pika }}"
    register: data

  - name: Use debug to show what is inside of our variable
    ansible.builtin.debug:
      msg: "{{ data }}"

  - name: Slice the variable further to only return the JSON
    ansible.builtin.debug:
      msg: "{{ data.get('json') }}"

  - name: Use debug with a loop across the JSON data
    ansible.builtin.debug:
      msg: "{{ item.get('name') }}"  
    loop: "{{ data.get('json').get('results') }}"

  - name: Use debug to display count
    ansible.builtin.debug:
      msg: "{{ data.get('json').get('count') }} pokemon in the database." 
